build: symbol ck_assert_ptr_ne requires check-0.9.10
openSUSE 12.3 ships with check-0.9.9 and subsequently fails to build
the tests. Change the call to look for check >= 0.9.10 where that
symbol is available.

Signed-off-by: Jan Engelhardt <jengelh@inai.de>